name: dexgraspnet
channels:
  - pytorch
  - pytorch3d
  - conda-forge
  - defaults
dependencies:
  - python=3.7  # isaac requires python < 3.9
  - pytorch=1.10
  - cudatoolkit=11.3
  - pytorch3d
  - transforms3d
  - trimesh
  - plotly
  - rtree
  - pip
  - pip:
    - urdf_parser_py
    - scipy
    - networkx
